import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Script from "next/script";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>La Stoppa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Benvenuto a La Stoppa</h1>
      </main>

      <Script
        src={`${process.env.NEXT_PUBLIC_API_URL}/api/overlay?key=${process.env.NEXT_PUBLIC_KEY}`}
      ></Script>
    </div>
  );
}
